title: 現実逃避跡地
author_1: 多口綾汰
author_2: tkmx
email_1: ayata.grobserver[at]gmail.com
email_2: TBD
description: > # this means to ignore newlines until "baseurl:"
 オリジナル小説サークル「現実逃避跡地」の情報を掲載しております．

twitter_username_1: ayata_taguchi_
twitter_username_2: tkmx0

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
